version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    networks:
      - db-internal
    environment:
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
    volumes:
      - /root/postgres/data:/var/lib/postgresql/data
      - /root/postgres/cert/server.crt:/var/lib/postgresql/server.crt
      - /root/postgres/cert/server.key:/var/lib/postgresql/server.key

networks:
  db-internal:
    driver: bridge
